- name: Install haproxy
  apt:
    name: haproxy
    state: present
    update_cache: true

- name: Copy HAProxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: Restart HAProxy
  service:
    name: haproxy
    state: restarted