apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: 1.13.0
apiServer:
  certSANs:
  - "balancer.ru-central1.internal"
controlPlaneEndpoint: "balancer.ru-central1.internal:6443"
networking:
  podSubnet: 10.244.0.0/16
