- name: ensure directories exist
  file:
    path: /etc/kubernetes/pki/etcd
    recurse: yes
    state: directory

- name: copy files from first master - 1
  copy:
    src: /tmp/etc/kubernetes/pki/{{item}}
    dest: /etc/kubernetes/pki/{{item}}
  with_items:
    - ca.crt
    - ca.key
    - sa.key
    - sa.pub
    - front-proxy-ca.crt
    - front-proxy-ca.key

- name: copy files from first master - 2
  copy:
    src: /tmp/etc/kubernetes/pki/etcd/{{item}}
    dest: /etc/kubernetes/pki/etcd/{{item}}
  with_items:
    - ca.crt
    - ca.key

- name: copy files from first master - 3
  copy:
    src: /tmp/etc/kubernetes/{{item}}
    dest: /etc/kubernetes/{{item}}
  with_items:
    - admin.conf

- name: join cluster
  shell: "{{ hostvars[groups['masters'][0]].join_command }} --experimental-control-plane >> node_joined.txt"
  args:
    chdir: $HOME
    creates: node_joined.txt