- hosts: masters[0]
  become: yes
  roles:
    - masters-first

- hosts: masters[1:]
  become: yes
  roles:
    - masters-rest

- hosts: masters[0]
  become: yes
  roles:
    - flannel
    - dashboard

